### ISSUE TITLE
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0

### ISSUE THREAD

**Issue by prodbyola** [bbc/peaks.js#433]
I'm trying to use peak.js in my Vue 3 project and I followed the documentation to load waveform data from the server. I can confirm the data was loaded successfully as I can see the "peaks" logged in the Peaks.init() function. However, the waveform is not displayed. Instead, I get the error stated above.

**Comment by jamesb93** [comment]
Try setting a fixed width and height on your image component? Either in `js` or `css`.

```html
<canvas id='sketch' />
```

```css
style {
    #sketch {
        width: 400px;
        height: 400px;
    }
}
```
}
